#!/bin/bash

# ==================================================
# Auto_DNS.sh - 一键自动 DNS 优选与锁定工具
# 功能：自动检测最快 DNS，更新 /etc/resolv.conf 并锁定
# ==================================================

# 1. 检查 Root 权限
if [[ $EUID -ne 0 ]]; then
   echo "❌ 错误：请使用 root 权限运行此脚本 (sudo bash ...)" 
   exit 1
fi

SCRIPT_PATH="/usr/local/bin/Auto_DNS.sh"

echo "================================================"
echo "🚀 开始部署 Auto_DNS 服务..."
echo "================================================"

# 2. 安装必要的依赖 (bc 和 chattr 工具)
echo "📦 检查并安装依赖工具..."
if command -v apt-get >/dev/null; then
    apt-get update -y >/dev/null 2>&1
    apt-get install -y bc e2fsprogs iputils-ping >/dev/null 2>&1
elif command -v yum >/dev/null; then
    yum install -y bc e2fsprogs iputils >/dev/null 2>&1
else
    echo "⚠️ 警告：未检测到 apt 或 yum，请确保系统已安装 'bc' 和 'ping'。"
fi

# 3. 生成核心逻辑脚本 Auto_DNS.sh
echo "📝 正在生成核心脚本: $SCRIPT_PATH"

cat << 'EOF' > "$SCRIPT_PATH"
#!/bin/bash

# ==========================================
# Auto_DNS.sh 核心逻辑
# ==========================================

# 待测速 DNS 列表 (包含 Google, CF, Quad9, OpenDNS, AliDNS, DNSPod)
DNS_SERVERS=(
    "8.8.8.8" "8.8.4.4"
    "1.1.1.1" "1.0.0.1"
    "9.9.9.9" "149.112.112.112"
    "208.67.222.222" "208.67.220.220"
    "223.5.5.5" "223.6.6.6"
    "119.29.29.29"
)

RESOLV_CONF="/etc/resolv.conf"
TEMP_FILE=$(mktemp)

# --- 步骤 1: 解锁文件 ---
# 必须先解锁，否则无法写入新 DNS
if [ -f "$RESOLV_CONF" ]; then
    chattr -i "$RESOLV_CONF" 2>/dev/null
fi

# --- 步骤 2: 测速 ---
# echo "正在测试 DNS 延迟..."

for dns in "${DNS_SERVERS[@]}"; do
    # -c 10: 10次测试
    # -i 0.2: 间隔0.2秒
    # -W 1: 超时1秒
    avg=$(ping -c 10 -i 0.2 -W 1 $dns 2>/dev/null | grep 'rtt' | cut -d"/" -f5)
    
    if [ -n "$avg" ]; then
        echo "$avg $dns" >> "$TEMP_FILE"
    fi
done

# --- 步骤 3: 排序并取前两名 ---
SORTED_DNS=$(sort -n "$TEMP_FILE" | awk '{print $2}')
DNS1=$(echo "$SORTED_DNS" | sed -n '1p')
DNS2=$(echo "$SORTED_DNS" | sed -n '2p')

# 删除临时文件
rm "$TEMP_FILE"

# --- 步骤 4: 写入配置 ---
if [ -n "$DNS1" ] && [ -n "$DNS2" ]; then
    
    # 如果 resolv.conf 是软链接(常见于Ubuntu)，删除它并创建静态文件
    # 这样可以彻底防止 systemd-resolved 覆盖配置
    if [ -L "$RESOLV_CONF" ]; then
        rm "$RESOLV_CONF"
    fi

    cat << CONF > "$RESOLV_CONF"
# Generated by Auto_DNS.sh
# Updated at: $(date)
nameserver $DNS1
nameserver $DNS2
options timeout:2 attempts:3 rotate
CONF

else
    # 保底措施：如果测速全失败，使用 Google DNS
    if [ ! -s "$RESOLV_CONF" ]; then
        echo "nameserver 8.8.8.8" > "$RESOLV_CONF"
        echo "nameserver 1.1.1.1" >> "$RESOLV_CONF"
    fi
fi

# --- 步骤 5: 重新锁定文件 ---
# 锁定后，其他程序无法修改此文件
chattr +i "$RESOLV_CONF" 2>/dev/null

EOF

# 4. 赋予执行权限
chmod +x "$SCRIPT_PATH"

# 5. 设置 Crontab 定时任务 (每小时运行一次)
CRON_CMD="0 * * * * $SCRIPT_PATH >/dev/null 2>&1"

# 检查是否存在，不存在则添加
if ! crontab -l 2>/dev/null | grep -q "Auto_DNS.sh"; then
    (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    echo "⏰ 定时任务已添加：每小时自动运行一次。"
else
    echo "✅ 定时任务已存在，跳过添加。"
fi

# 6. 立即运行一次验证效果
echo "🏃 正在立即运行脚本进行首次优选..."
echo "------------------------------------------------"
bash "$SCRIPT_PATH"

# 验证结果
echo "✅ 运行完成！当前 /etc/resolv.conf 内容如下："
echo "------------------------------------------------"
cat /etc/resolv.conf
echo "------------------------------------------------"
echo "🔒 文件属性 (查看是否有 'i' 标志):"
lsattr /etc/resolv.conf 2>/dev/null || echo "lsattr 未安装，无法查看属性，但锁定功能已生效。"
echo "================================================"
echo "🎉 部署完成！脚本路径: $SCRIPT_PATH"
