#!/bin/bash

# ==================================================
# Auto_DNS.sh - 一键自动 DNS 优选与锁定工具
# 功能：自动检测最快 DNS (综合 ping+解析速度)，
#       更新 /etc/resolv.conf 并锁定
# ==================================================

# ---------- 1. Root 检查 ----------
if [[ $EUID -ne 0 ]]; then
  echo "❌ 错误：请使用 root 权限运行此脚本 (sudo bash ...)"
  exit 1
fi

# ---------- 安装路径 ----------
SCRIPT_PATH="/usr/local/bin/Auto_DNS.sh"

# ---------- 海外基准测试域名 (只用海外站) ----------
BENCHMARK_DOMAINS=(
  "google.com"
  "youtube.com"
  "github.com"
  "reddit.com"
  "stackoverflow.com"
  "twitter.com"
  "wikipedia.org"
)

# ---------- 日志 ----------
LOG_FILE="/var/log/Auto_DNS.log"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg"
  echo "$msg" >> "$LOG_FILE"
}

# ==================================================
echo "================================================"
echo "🚀 开始部署 Auto_DNS 服务..."
echo "================================================"

# ---------- 2. 依赖检查 & 安装 ----------
echo "📦 检查并安装依赖工具..."
if command -v apt-get >/dev/null; then
  apt-get update -y >/dev/null 2>&1
  apt-get install -y bc e2fsprogs iputils-ping dnsutils >/dev/null 2>&1
elif command -v yum >/dev/null; then
  yum install -y bc e2fsprogs iputils bind-utils >/dev/null 2>&1
else
  echo "⚠️ 警告：未检测到 apt 或 yum，请确保已安装 bc/ping/dig"
fi

# ---------- 3. 生成核心脚本 ----------
echo "📝 生成核心脚本: $SCRIPT_PATH"

cat << 'EOFMARKER' > "$SCRIPT_PATH"
#!/bin/bash
# ==========================================
# Auto_DNS.sh 核心逻辑
# 综合 ping 延迟 + dig 解析速度 评分
# ==========================================

# ---------- 配置 ----------
DNS_SERVERS=(
  "1.1.1.1" "1.0.0.1"
  "8.8.8.8" "8.8.4.4"
  "9.9.9.9" "149.112.112.112"
  "208.67.222.222" "208.67.220.220"
)

BENCHMARK_DOMAINS=(
  "google.com"
  "youtube.com"
  "github.com"
  "reddit.com"
  "stackoverflow.com"
  "twitter.com"
  "wikipedia.org"
)

RESOLV_CONF="/etc/resolv.conf"
TEMP_FILE=$(mktemp)
LOGFILE="/var/log/Auto_DNS.log"
PING_COUNT=5
DIG_SAMPLES=2
DIG_TIMEOUT=5

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg" >> "$LOGFILE"
}

# ---------- 解锁 ----------
[ -f "$RESOLV_CONF" ] && chattr -i "$RESOLV_CONF" 2>/dev/null

# ---------- 开始测速 ----------
log "=== Auto_DNS 检测开始 ==="

for dns in "${DNS_SERVERS[@]}"; do
  # --- ① Ping 测试 (网络延迟) ---
  ping_result=$(ping -c "$PING_COUNT" -i 0.2 -W 2 "$dns" 2>/dev/null)
  ping_avg=$(echo "$ping_result" | grep 'rtt' | cut -d'/' -f5)
  
  # 丢包惩罚
  loss=$(echo "$ping_result" | grep -oP '\d+(?=% packet loss)' || echo "100")
  if [ -z "$ping_avg" ] || [ "$loss" -ge 50 ] 2>/dev/null; then
    log "  ${dns} → ping 失败或丢包>50%，跳过"
    continue
  fi
  ping_int=${ping_avg%.*}

  # --- ② DNS 解析测试 ---
  total=0
  count=0
  for domain in "${BENCHMARK_DOMAINS[@]}"; do
    for ((i=0; i<DIG_SAMPLES; i++)); do
      r=$RANDOM
      t=$(dig @"$dns" "$r.$domain" +stats +time="$DIG_TIMEOUT" +tries=1 2>/dev/null | grep "Query time" | grep -oP '\d+')
      if [ -n "$t" ] && [ "$t" -lt 5000 ] 2>/dev/null; then
        total=$((total + t))
        count=$((count + 1))
      fi
    done
  done

  if [ "$count" -eq 0 ]; then
    log "  ${dns} → ping=${ping_avg}ms dig=失败"
    continue
  fi
  dig_avg=$((total / count))

  # --- ③ 综合评分 (ping*30% + dig*70%) ---
  combined=$(( (ping_int * 3 + dig_avg * 7) / 10 ))
  echo "$combined|$ping_avg|$dig_avg|$dns" >> "$TEMP_FILE"
  log "  ${dns} → ping=${ping_avg}ms dig=${dig_avg}ms 综合=${combined}"
done

# ---------- 排序取前2 ----------
SORTED=$(sort -n "$TEMP_FILE")
DNS1=$(echo "$SORTED" | sed -n '1p' | cut -d'|' -f4)
DNS2=$(echo "$SORTED" | sed -n '2p' | cut -d'|' -f4)

rm -f "$TEMP_FILE"

# ---------- 写入 resolv.conf ----------
if [ -n "$DNS1" ] && [ -n "$DNS2" ]; then
  # 处理软链接（如 Ubuntu systemd-resolved）
  if [ -L "$RESOLV_CONF" ]; then
    rm -f "$RESOLV_CONF"
  fi

  cat << CONF > "$RESOLV_CONF"
# Generated by Auto_DNS.sh
# Updated at: $(date)
nameserver $DNS1
nameserver $DNS2
options timeout:2 attempts:3 rotate
CONF

  log "✅ 已更新: ${DNS1} ${DNS2}"
else
  # 保底
  if [ ! -s "$RESOLV_CONF" ]; then
    echo "nameserver 8.8.8.8" > "$RESOLV_CONF"
    echo "nameserver 1.1.1.1" >> "$RESOLV_CONF"
    log "⚠️ 测速失败，使用保底 DNS"
  fi
fi

# ---------- 锁定 ----------
chattr +i "$RESOLV_CONF" 2>/dev/null
log "=== Auto_DNS 检测完成 ==="

EOFMARKER

# ---------- 4. 赋予执行权限 ----------
chmod +x "$SCRIPT_PATH"

# ---------- 5. Cron (每小时) ----------
CRON_CMD="0 * * * * $SCRIPT_PATH >/dev/null 2>&1"
if ! crontab -l 2>/dev/null | grep -q "Auto_DNS.sh"; then
  (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
  echo "⏰ 定时任务已添加：每小时自动运行一次。"
else
  echo "✅ 定时任务已存在，跳过添加。"
fi

# ---------- 6. 首次运行 ----------
echo "🏃 正在立即运行脚本进行首次优选..."
echo "------------------------------------------------"
bash "$SCRIPT_PATH"

# 输出最终结果
echo "================================================"
echo "📋 当前 /etc/resolv.conf:"
echo "------------------------------------------------"
cat /etc/resolv.conf
echo "------------------------------------------------"
echo "🔒 文件属性:"
lsattr /etc/resolv.conf 2>/dev/null || echo "   (lsattr 不可用，锁定已执行)"
echo "================================================"
echo "🎉 部署完成！"
echo "   脚本: $SCRIPT_PATH"
echo "   日志: tail -f $LOG_FILE"
echo "   手动运行: bash $SCRIPT_PATH"
echo "================================================"
